/**
 * Type definitions for LexOrbital Surveillance System
 * 
 * These types define the contract for all surveillance modules.
 * Each module must produce a JSON report conforming to these interfaces.
 * 
 * @module surveillance.types
 * @version 1.0.0
 */

/**
 * Health status of a check or module
 */
export type HealthStatus = 'healthy' | 'warning' | 'critical' | 'unknown';

/**
 * Severity level for alerts
 */
export type AlertSeverity = 'info' | 'warning' | 'critical';

/**
 * Supported surveillance modules
 */
export type SurveillanceModule = 
  | 'resources' 
  | 'security' 
  | 'services' 
  | 'network' 
  | 'integrity';

/**
 * Metadata for a surveillance report
 */
export interface ReportMetadata {
  /** Module name */
  module: SurveillanceModule;
  
  /** Schema version */
  version: string;
  
  /** ISO 8601 timestamp */
  timestamp: string;
  
  /** Hostname of the server */
  hostname: string;
  
  /** Execution time in milliseconds */
  executionTime: number;
}

/**
 * Threshold configuration for a check
 */
export interface Threshold {
  /** Warning threshold value */
  warning: number;
  
  /** Critical threshold value */
  critical: number;
  
  /** Unit of measurement (optional) */
  unit?: string;
}

/**
 * Individual check result
 */
export interface Check {
  /** Unique identifier for the check */
  id: string;
  
  /** Human-readable name */
  name: string;
  
  /** Check status */
  status: HealthStatus;
  
  /** Status message or description */
  message: string;
  
  /** Measured value (optional) */
  value?: number | string | boolean;
  
  /** Threshold configuration (optional) */
  threshold?: Threshold;
  
  /** Tags for categorization (optional) */
  tags?: string[];
  
  /** Additional metadata (optional) */
  metadata?: Record<string, unknown>;
}

/**
 * Metric value with timestamp
 */
export interface Metric {
  /** Metric value */
  value: number;
  
  /** Unit of measurement */
  unit: string;
  
  /** ISO 8601 timestamp */
  timestamp: string;
  
  /** Metric labels (optional) */
  labels?: Record<string, string>;
}

/**
 * Alert generated by a surveillance module
 */
export interface Alert {
  /** Alert severity */
  severity: AlertSeverity;
  
  /** Source module or check */
  source: string;
  
  /** Alert message */
  message: string;
  
  /** ISO 8601 timestamp */
  timestamp: string;
  
  /** Additional alert data (optional) */
  data?: Record<string, unknown>;
  
  /** Alert ID for tracking (optional) */
  id?: string;
}

/**
 * Base surveillance report structure
 * 
 * All surveillance modules must produce a report conforming to this interface.
 */
export interface SurveillanceReport {
  /** Report metadata */
  metadata: ReportMetadata;
  
  /** Overall health status */
  status: HealthStatus;
  
  /** List of checks performed */
  checks: Check[];
  
  /** Collected metrics (optional) */
  metrics?: Record<string, Metric>;
  
  /** Generated alerts (optional) */
  alerts?: Alert[];
}

/**
 * Summary statistics for the global report
 */
export interface SurveillanceSummary {
  /** Total number of checks performed */
  totalChecks: number;
  
  /** Number of healthy checks */
  healthyChecks: number;
  
  /** Number of checks with warnings */
  warningChecks: number;
  
  /** Number of critical checks */
  criticalChecks: number;
  
  /** Number of unknown status checks */
  unknownChecks?: number;
}

/**
 * Global surveillance report aggregating all modules
 */
export interface GlobalSurveillanceReport {
  /** Global metadata */
  metadata: {
    /** Schema version */
    version: string;
    
    /** ISO 8601 timestamp */
    timestamp: string;
    
    /** Hostname of the server */
    hostname: string;
    
    /** Total execution time in milliseconds */
    totalExecutionTime: number;
    
    /** Number of modules executed */
    modulesExecuted: number;
    
    /** Number of modules failed */
    modulesFailed?: number;
  };
  
  /** Global health status (worst-case from all modules) */
  globalStatus: HealthStatus;
  
  /** Individual module reports */
  modules: Partial<Record<SurveillanceModule, SurveillanceReport>>;
  
  /** Aggregated summary */
  summary: SurveillanceSummary;
  
  /** Aggregated alerts from all modules */
  alerts: Alert[];
}

/**
 * Configuration for a surveillance module
 */
export interface SurveillanceConfig {
  /** Module to configure */
  module: SurveillanceModule;
  
  /** Enable or disable the module */
  enabled: boolean;
  
  /** Execution interval in seconds */
  interval?: number;
  
  /** Custom thresholds */
  thresholds?: Record<string, Threshold>;
  
  /** Module-specific options */
  options?: Record<string, unknown>;
}

/**
 * Surveillance system configuration
 */
export interface SurveillanceSystemConfig {
  /** System-level settings */
  system: {
    /** Hostname override (optional) */
    hostname?: string;
    
    /** Global output directory */
    outputDir: string;
    
    /** Enable global alerts */
    enableAlerts: boolean;
    
    /** Alert email recipients (optional) */
    alertEmails?: string[];
    
    /** API endpoint for console orbitale (optional) */
    apiEndpoint?: string;
    
    /** API authentication token (optional) */
    apiToken?: string;
  };
  
  /** Module configurations */
  modules: SurveillanceConfig[];
  
  /** GDPR settings */
  gdpr: {
    /** Enable IP pseudonymization */
    pseudonymizeIps: boolean;
    
    /** Data retention in days */
    retentionDays: number;
    
    /** Enable audit logging */
    enableAuditLog: boolean;
  };
}

/**
 * API response from console orbitale
 */
export interface SurveillanceApiResponse {
  /** Response status */
  status: 'received' | 'error';
  
  /** Unique report ID */
  reportId?: string;
  
  /** Timestamp of receipt */
  timestamp: string;
  
  /** Error message if status is 'error' */
  error?: string;
}

